#!/busybox sh
###################################################
# ===== Neo_Chen's 486 Bootable Floppy Disk ===== #
###################################################

## Colors
ESC="\e"
RESET="${ESC}[0m"	#Reset all attributes
BRIGHT="${ESC}[1m"	#Bright
DIM="${ESC}[2m"	#Dim
BLINK="${ESC}[5m"	#Blink
#Foreground Colours
FBLACK="${ESC}[30m"	#Black
FRED="${ESC}[31m"	#Red
FGREEN="${ESC}[32m"	#Green
FYELLOW="${ESC}[33m"	#Yellow
FBLUE="${ESC}[34m"	#Blue
FMAGENTA="${ESC}[35m"	#Magenta
FCYAN="${ESC}[36m"	#Cyan
FWHITE="${ESC}[37m"	#White
#Background Colours
BBLACK="${ESC}[40m"	#Black
BRED="${ESC}[41m"	#Red
BGREEN="${ESC}[42m"	#Green
BYELLOW="${ESC}[43m"	#Yellow
BBLUE="${ESC}[44m"	#Blue
BMAGENTA="${ESC}[45m"	#Magenta
BCYAN="${ESC}[46m"	#Cyan
BWHITE="${ESC}[47m"	#White

# Normal Message
msg_echo()
{
	echo -e "${BBLUE}>>${RESET} ${BRIGHT}${FYELLOW}${*}${RESET}"
}

# Error Message
err_echo()
{
	echo -e "${BRIGHT}${BRED}>>${RESET} ${BRIGHT}${FRED}${*}${RESET}"
}

# Sub-message

sub_echo()
{
	echo -e "\t${BRIGHT}>> ${1}${RESET}"
}

# Important Environment Variable
export PATH="/bin"

echo -e "${FCYAN}Making /bin${RESET}"
/busybox mkdir -p /bin /etc /etc/udev /sys /proc /cd /tmp /new_root
echo -e "${FCYAN}Installing Binaries${RESET}"
/busybox --install -s /bin

msg_echo "Mounting /proc /sys /dev /tmp"
mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t devtmpfs devtmpfs /dev
mount -t tmpfs tmpfs /tmp
msg_echo "Triggering mdev"
ln -sf /proc/mtab /etc/mtab
mdev -s

touch /etc/fstab

PATH="/bin"

msg_echo "Finding Installation CD"
if mount LABEL=AOSC_INSTCD /cd ; then
		sub_echo "Found & Mounted CD, switch_root into it."
		ln -s /cd/lib /lib
		/cd/busybox modprobe overlay &&
			sub_echo "Loaded overlayfs module"

		mkdir /tmp/work /tmp/updir
		mount -t overlay -o lowerdir=/cd,upperdir=/tmp/updir,workdir=/tmp/work overlay /new_root &&
		sub_echo "Switching Root!! There's no way to return from now on."
		exec switch_root /new_root /init
fi

date +"%FT%T%z"

err_echo "Unable to mount the installation CD, launching shell."
exec cttyhack ash
